const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 29/01/2025 (Quarta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5088",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "7501",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "5439",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "1351",
          "13",
          "Galo"
        ],
        [
          "5º",
          "5950",
          "13",
          "Galo"
        ],
        [
          "6º",
          "6299",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "0757",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "2043",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "7166",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "0113",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 29/01/2025 (Quarta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7772",
          "18",
          "Porco"
        ],
        [
          "2º",
          "5493",
          "24",
          "Veado"
        ],
        [
          "3º",
          "5130",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "0038",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "9572",
          "18",
          "Porco"
        ],
        [
          "6º",
          "1574",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "1718",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "3791",
          "23",
          "Urso"
        ],
        [
          "9º",
          "7548",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "4317",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 29/01/2025 (Quarta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1973",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "4101",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "0780",
          "20",
          "Peru"
        ],
        [
          "4º",
          "4904",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "3931",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "1990",
          "23",
          "Urso"
        ],
        [
          "7º",
          "0477",
          "20",
          "Peru"
        ],
        [
          "8º",
          "4515",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "4397",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "4554",
          "14",
          "Gato"
        ]
      ]
    },
    {
      "titulo": "19h FEDERAL - MALUCA - BA - Resultado do dia 29/01/2025 (Quarta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3196",
          "24",
          "Veado"
        ],
        [
          "2º",
          "6770",
          "18",
          "Porco"
        ],
        [
          "3º",
          "0535",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "7375",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "2302",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "2347",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "2989",
          "23",
          "Urso"
        ],
        [
          "8º",
          "2899",
          "25",
          "Vaca"
        ],
        [
          "9º",
          "2517",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "1426",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "21h - MALUCA - BA - Resultado do dia 29/01/2025 (Quarta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9299",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "1055",
          "14",
          "Gato"
        ],
        [
          "3º",
          "3878",
          "20",
          "Peru"
        ],
        [
          "4º",
          "0588",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "5076",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "0728",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "8184",
          "21",
          "Touro"
        ],
        [
          "8º",
          "5310",
          "03",
          "Burro"
        ],
        [
          "9º",
          "1747",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "7042",
          "11",
          "Cavalo"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 30/01/2025 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9445",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "0384",
          "21",
          "Touro"
        ],
        [
          "3º",
          "1739",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "8362",
          "16",
          "Leão"
        ],
        [
          "5º",
          "5729",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "4878",
          "20",
          "Peru"
        ],
        [
          "7º",
          "1375",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "6142",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "5632",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "3536",
          "09",
          "Cobra"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho A FEDERAL DO BRASIL CE - Ceará Federal",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7063",
          "16",
          "Leão"
        ],
        [
          "2º",
          "3571",
          "18",
          "Porco"
        ],
        [
          "3º",
          "7379",
          "20",
          "Peru"
        ],
        [
          "4º",
          "5506",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2032",
          "08",
          "Camelo"
        ],
        [
          "6º [soma]",
          "5551",
          "",
          ""
        ],
        [
          "7º [mult]",
          "261",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5350",
          "13",
          "Galo"
        ],
        [
          "2º",
          "4136",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "2404",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "0785",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "9260",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "3572",
          "18",
          "Porco"
        ],
        [
          "7º",
          "1754",
          "14",
          "Gato"
        ],
        [
          "8º",
          "7107",
          "02",
          "Águia"
        ],
        [
          "9º",
          "4987",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "7551",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7014",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "2524",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "1387",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "7030",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "7095",
          "24",
          "Veado"
        ],
        [
          "6º",
          "1410",
          "03",
          "Burro"
        ],
        [
          "7º",
          "8088",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "4971",
          "18",
          "Porco"
        ],
        [
          "9º",
          "7685",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "2179",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7992",
          "23",
          "Urso"
        ],
        [
          "2º",
          "4734",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "4974",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "0269",
          "18",
          "Porco"
        ],
        [
          "5º",
          "6553",
          "14",
          "Gato"
        ],
        [
          "6º",
          "9820",
          "05",
          "Cachorro"
        ],
        [
          "7º",
          "9095",
          "24",
          "Veado"
        ],
        [
          "8º",
          "0769",
          "18",
          "Porco"
        ],
        [
          "9º",
          "9410",
          "03",
          "Burro"
        ],
        [
          "10º",
          "8358",
          "15",
          "Jacaré"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7458",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "1366",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "6546",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "9997",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "2159",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "4678",
          "20",
          "Peru"
        ],
        [
          "7º",
          "2650",
          "13",
          "Galo"
        ],
        [
          "8º",
          "0591",
          "23",
          "Urso"
        ],
        [
          "9º",
          "9314",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "1849",
          "13",
          "Galo"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0852",
          "13",
          "Galo"
        ],
        [
          "2º",
          "4552",
          "13",
          "Galo"
        ],
        [
          "3º",
          "2722",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "2604",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "8759",
          "15",
          "Jacaré"
        ],
        [
          "6º [soma]",
          "9489",
          "",
          ""
        ],
        [
          "7º [mult]",
          "878",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0852",
          "13",
          "Galo"
        ],
        [
          "2º",
          "4552",
          "13",
          "Galo"
        ],
        [
          "3º",
          "2722",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "2604",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "8759",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "0422",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "8576",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "5520",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "2224",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "6231",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6115",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "1593",
          "24",
          "Veado"
        ],
        [
          "3º",
          "8810",
          "03",
          "Burro"
        ],
        [
          "4º",
          "2038",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "3655",
          "14",
          "Gato"
        ],
        [
          "6º [soma]",
          "2211",
          "",
          ""
        ],
        [
          "7º [mult]",
          "741",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6115",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "1593",
          "24",
          "Veado"
        ],
        [
          "3º",
          "8810",
          "03",
          "Burro"
        ],
        [
          "4º",
          "2038",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "3655",
          "14",
          "Gato"
        ],
        [
          "6º",
          "6182",
          "21",
          "Touro"
        ],
        [
          "7º",
          "1580",
          "20",
          "Peru"
        ],
        [
          "8º",
          "1913",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "5308",
          "02",
          "Águia"
        ],
        [
          "10º",
          "7194",
          "24",
          "Veado"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8827",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "0655",
          "14",
          "Gato"
        ],
        [
          "3º",
          "9613",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "6796",
          "24",
          "Veado"
        ],
        [
          "5º",
          "8210",
          "03",
          "Burro"
        ],
        [
          "6º",
          "8096",
          "24",
          "Veado"
        ],
        [
          "7º",
          "8667",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "2519",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "7536",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "0919",
          "05",
          "Cachorro"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9204",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8437",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "9084",
          "21",
          "Touro"
        ],
        [
          "4º",
          "6260",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "4277",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "7262",
          "",
          ""
        ],
        [
          "7º [mult]",
          "654",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9204",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8437",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "9084",
          "21",
          "Touro"
        ],
        [
          "4º",
          "6260",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "4277",
          "20",
          "Peru"
        ],
        [
          "6º",
          "9896",
          "24",
          "Veado"
        ],
        [
          "7º",
          "2402",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "0386",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "4740",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "4686",
          "22",
          "Tigre"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9311",
          "03",
          "Burro"
        ],
        [
          "2º",
          "6157",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "2725",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "6442",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4095",
          "24",
          "Veado"
        ],
        [
          "6º [soma]",
          "8730",
          "",
          ""
        ],
        [
          "7º [mult]",
          "327",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9311",
          "03",
          "Burro"
        ],
        [
          "2º",
          "6157",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "2725",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "6442",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4095",
          "24",
          "Veado"
        ],
        [
          "6º",
          "9626",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "3174",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "1524",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "1752",
          "13",
          "Galo"
        ],
        [
          "10º",
          "4806",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4775",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "9388",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "3295",
          "24",
          "Veado"
        ],
        [
          "4º",
          "8759",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "3753",
          "14",
          "Gato"
        ],
        [
          "6º [soma]",
          "9970",
          "",
          ""
        ],
        [
          "7º [mult]",
          "827",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4775",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "9388",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "3295",
          "24",
          "Veado"
        ],
        [
          "4º",
          "8759",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "3753",
          "14",
          "Gato"
        ],
        [
          "6º",
          "4938",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "7327",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "7895",
          "24",
          "Veado"
        ],
        [
          "9º",
          "5859",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "5989",
          "23",
          "Urso"
        ]
      ]
    }
  ]
};