const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4021",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "3046",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "1207",
          "02",
          "Águia"
        ],
        [
          "4º",
          "1076",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "3077",
          "20",
          "Peru"
        ],
        [
          "6º",
          "3703",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "8437",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "6683",
          "21",
          "Touro"
        ],
        [
          "9º",
          "5780",
          "20",
          "Peru"
        ],
        [
          "10º",
          "9496",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5970",
          "18",
          "Porco"
        ],
        [
          "2º",
          "4985",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "3854",
          "14",
          "Gato"
        ],
        [
          "4º",
          "8064",
          "16",
          "Leão"
        ],
        [
          "5º",
          "3602",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "1487",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "2204",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "5818",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "8526",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "0732",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7645",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "1951",
          "13",
          "Galo"
        ],
        [
          "3º",
          "0888",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "6420",
          "05",
          "Cachorro"
        ],
        [
          "5º",
          "2442",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "5343",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "0881",
          "21",
          "Touro"
        ],
        [
          "8º",
          "5265",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "8622",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "3519",
          "05",
          "Cachorro"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1134",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "0200",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "7042",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "6761",
          "16",
          "Leão"
        ],
        [
          "5º",
          "7703",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "5683",
          "21",
          "Touro"
        ],
        [
          "7º",
          "7647",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "8830",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "0373",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "6949",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8345",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "0899",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "6587",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "4450",
          "13",
          "Galo"
        ],
        [
          "5º",
          "2063",
          "16",
          "Leão"
        ],
        [
          "6º",
          "8521",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "5824",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "2108",
          "02",
          "Águia"
        ],
        [
          "9º",
          "6847",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "2370",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 30/09/2025 (Terça-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6017",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "4896",
          "24",
          "Veado"
        ],
        [
          "3º",
          "2854",
          "14",
          "Gato"
        ],
        [
          "4º",
          "0815",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "2442",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "8505",
          "02",
          "Águia"
        ],
        [
          "7º",
          "6283",
          "21",
          "Touro"
        ],
        [
          "8º",
          "2684",
          "21",
          "Touro"
        ],
        [
          "9º",
          "2513",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "9153",
          "14",
          "Gato"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9396",
          "24",
          "Veado"
        ],
        [
          "2º",
          "9761",
          "16",
          "Leão"
        ],
        [
          "3º",
          "3375",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "2269",
          "18",
          "Porco"
        ],
        [
          "5º",
          "1484",
          "21",
          "Touro"
        ],
        [
          "6º",
          "5753",
          "14",
          "Gato"
        ],
        [
          "7º",
          "1054",
          "14",
          "Gato"
        ],
        [
          "8º",
          "8772",
          "18",
          "Porco"
        ],
        [
          "9º",
          "6548",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "4731",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6355",
          "14",
          "Gato"
        ],
        [
          "2º",
          "9178",
          "20",
          "Peru"
        ],
        [
          "3º",
          "1855",
          "14",
          "Gato"
        ],
        [
          "4º",
          "8705",
          "02",
          "Águia"
        ],
        [
          "5º",
          "0444",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "8473",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "6781",
          "21",
          "Touro"
        ],
        [
          "8º",
          "2844",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "8991",
          "23",
          "Urso"
        ],
        [
          "10º",
          "3519",
          "05",
          "Cachorro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6149",
          "13",
          "Galo"
        ],
        [
          "2º",
          "3338",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "3139",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "6312",
          "03",
          "Burro"
        ],
        [
          "5º",
          "1777",
          "20",
          "Peru"
        ],
        [
          "6º",
          "1522",
          "06",
          "Cabra"
        ],
        [
          "7º",
          "4346",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "1166",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "7531",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "4409",
          "03",
          "Burro"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7132",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "0638",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "5802",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7823",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0336",
          "09",
          "Cobra"
        ],
        [
          "6º [soma]",
          "1731",
          "",
          ""
        ],
        [
          "7º [mult]",
          "550",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7132",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "0638",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "5802",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7823",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0336",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "7057",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "1688",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "3302",
          "01",
          "Avestruz"
        ],
        [
          "9º",
          "2823",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "6601",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2387",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "9027",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "3273",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "7282",
          "21",
          "Touro"
        ],
        [
          "5º",
          "8003",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "9972",
          "",
          ""
        ],
        [
          "7º [mult]",
          "547",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2387",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "9027",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "3273",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "7282",
          "21",
          "Touro"
        ],
        [
          "5º",
          "8003",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "2937",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "3022",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "8278",
          "20",
          "Peru"
        ],
        [
          "9º",
          "7732",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "1941",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5996",
          "24",
          "Veado"
        ],
        [
          "2º",
          "9088",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "9968",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "9570",
          "18",
          "Porco"
        ],
        [
          "5º",
          "9846",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "4468",
          "",
          ""
        ],
        [
          "7º [mult]",
          "491",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5996",
          "24",
          "Veado"
        ],
        [
          "2º",
          "9088",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "9968",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "9570",
          "18",
          "Porco"
        ],
        [
          "5º",
          "9846",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "5999",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "9095",
          "24",
          "Veado"
        ],
        [
          "8º",
          "9867",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "6880",
          "20",
          "Peru"
        ],
        [
          "10º",
          "6309",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6146",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "7590",
          "23",
          "Urso"
        ],
        [
          "3º",
          "6830",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "3659",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "0470",
          "18",
          "Porco"
        ],
        [
          "6º [soma]",
          "4695",
          "",
          ""
        ],
        [
          "7º [mult]",
          "648",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6146",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "7590",
          "23",
          "Urso"
        ],
        [
          "3º",
          "6830",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "3659",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "0470",
          "18",
          "Porco"
        ],
        [
          "6º",
          "6763",
          "16",
          "Leão"
        ],
        [
          "7º",
          "1586",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "4935",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "6009",
          "03",
          "Burro"
        ],
        [
          "10º",
          "3988",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4867",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7404",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7033",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "3262",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0045",
          "12",
          "Elefante"
        ],
        [
          "6º [soma]",
          "2611",
          "",
          ""
        ],
        [
          "7º [mult]",
          "035",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 16h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4867",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7404",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7033",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "3262",
          "16",
          "Leão"
        ],
        [
          "5º",
          "0045",
          "12",
          "Elefante"
        ],
        [
          "6º",
          "4773",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "8402",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "6036",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "7432",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "9254",
          "14",
          "Gato"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7146",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "1591",
          "23",
          "Urso"
        ],
        [
          "3º",
          "1483",
          "21",
          "Touro"
        ],
        [
          "4º",
          "4951",
          "13",
          "Galo"
        ],
        [
          "5º",
          "8764",
          "16",
          "Leão"
        ],
        [
          "6º [soma]",
          "3935",
          "",
          ""
        ],
        [
          "7º [mult]",
          "369",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 18h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7146",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "1591",
          "23",
          "Urso"
        ],
        [
          "3º",
          "1483",
          "21",
          "Touro"
        ],
        [
          "4º",
          "4951",
          "13",
          "Galo"
        ],
        [
          "5º",
          "8764",
          "16",
          "Leão"
        ],
        [
          "6º",
          "7114",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "1549",
          "13",
          "Galo"
        ],
        [
          "8º",
          "4985",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "6131",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "3714",
          "04",
          "Borboleta"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho CAMPINA GRANDE - PB, 9:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1893",
          "24",
          "Veado"
        ],
        [
          "2º",
          "7480",
          "20",
          "Peru"
        ],
        [
          "3º",
          "5040",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "3358",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "4389",
          "23",
          "Urso"
        ],
        [
          "6º",
          "1753",
          "14",
          "Gato"
        ],
        [
          "7º",
          "8403",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "9845",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "3008",
          "02",
          "Águia"
        ],
        [
          "10º",
          "5169",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2299",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "8724",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "2242",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "8471",
          "18",
          "Porco"
        ],
        [
          "5º",
          "8987",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "2828",
          "07",
          "Carneiro"
        ],
        [
          "7º",
          "2724",
          "06",
          "Cabra"
        ],
        [
          "8º",
          "9247",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "9421",
          "06",
          "Cabra"
        ],
        [
          "10º",
          "4943",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho CAMPINA GRANDE - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7202",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "6975",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "1764",
          "16",
          "Leão"
        ],
        [
          "4º",
          "0827",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "8383",
          "21",
          "Touro"
        ],
        [
          "6º",
          "7610",
          "03",
          "Burro"
        ],
        [
          "7º",
          "2978",
          "20",
          "Peru"
        ],
        [
          "8º",
          "0762",
          "16",
          "Leão"
        ],
        [
          "9º",
          "2547",
          "12",
          "Elefante"
        ],
        [
          "10º",
          "9048",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0262",
          "16",
          "Leão"
        ],
        [
          "2º",
          "2313",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "8178",
          "20",
          "Peru"
        ],
        [
          "4º",
          "5623",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "1379",
          "20",
          "Peru"
        ],
        [
          "6º",
          "0285",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "2316",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "6172",
          "18",
          "Porco"
        ],
        [
          "9º",
          "2383",
          "21",
          "Touro"
        ],
        [
          "10º",
          "8911",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho CAMPINA GRANDE - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2624",
          "06",
          "Cabra"
        ],
        [
          "2º",
          "1439",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "8647",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "6630",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "4778",
          "20",
          "Peru"
        ],
        [
          "6º",
          "2186",
          "22",
          "Tigre"
        ],
        [
          "7º",
          "6466",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "2343",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "4970",
          "18",
          "Porco"
        ],
        [
          "10º",
          "0083",
          "21",
          "Touro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5178",
          "20",
          "Peru"
        ],
        [
          "2º",
          "7909",
          "03",
          "Burro"
        ],
        [
          "3º",
          "4023",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "7376",
          "19",
          "Pavão"
        ],
        [
          "5º",
          "6714",
          "04",
          "Borboleta"
        ],
        [
          "6º",
          "5747",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "1903",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "7027",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "8936",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "4813",
          "04",
          "Borboleta"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho CAMPINA GRANDE - PB, 15:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5792",
          "23",
          "Urso"
        ],
        [
          "2º",
          "8596",
          "24",
          "Veado"
        ],
        [
          "3º",
          "7737",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "5658",
          "15",
          "Jacaré"
        ],
        [
          "5º",
          "3218",
          "05",
          "Cachorro"
        ],
        [
          "6º",
          "5875",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "7576",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "9935",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "2678",
          "20",
          "Peru"
        ],
        [
          "10º",
          "7065",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 15:45h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1136",
          "09",
          "Cobra"
        ],
        [
          "2º",
          "0762",
          "16",
          "Leão"
        ],
        [
          "3º",
          "4687",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "8096",
          "24",
          "Veado"
        ],
        [
          "5º",
          "3234",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "1048",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "1760",
          "15",
          "Jacaré"
        ],
        [
          "8º",
          "3689",
          "23",
          "Urso"
        ],
        [
          "9º",
          "6276",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "0688",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 18h",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3219",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "5579",
          "20",
          "Peru"
        ],
        [
          "3º",
          "2936",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "0180",
          "20",
          "Peru"
        ],
        [
          "5º",
          "7405",
          "02",
          "Águia"
        ],
        [
          "6º",
          "3520",
          "05",
          "Cachorro"
        ],
        [
          "7º",
          "2591",
          "23",
          "Urso"
        ],
        [
          "8º",
          "1738",
          "10",
          "Coelho"
        ],
        [
          "9º",
          "9960",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "7128",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho CAMPINA GRANDE - PB, 18:05",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2466",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "0663",
          "16",
          "Leão"
        ],
        [
          "3º",
          "3948",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "7186",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "5573",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "2037",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "4691",
          "23",
          "Urso"
        ],
        [
          "8º",
          "6648",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "6386",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "9598",
          "25",
          "Vaca"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7579",
          "20",
          "Peru"
        ],
        [
          "2º",
          "6542",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "7153",
          "14",
          "Gato"
        ],
        [
          "4º",
          "2799",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "1188",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "5261",
          "",
          ""
        ],
        [
          "7º [mult]",
          "581",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7579",
          "20",
          "Peru"
        ],
        [
          "2º",
          "6542",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "7153",
          "14",
          "Gato"
        ],
        [
          "4º",
          "2799",
          "25",
          "Vaca"
        ],
        [
          "5º",
          "1188",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "7672",
          "18",
          "Porco"
        ],
        [
          "7º",
          "5517",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "7459",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "9239",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "5148",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0820",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "4011",
          "03",
          "Burro"
        ],
        [
          "3º",
          "5161",
          "16",
          "Leão"
        ],
        [
          "4º",
          "3971",
          "18",
          "Porco"
        ],
        [
          "5º",
          "7472",
          "18",
          "Porco"
        ],
        [
          "6º [soma]",
          "1435",
          "",
          ""
        ],
        [
          "7º [mult]",
          "289",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0820",
          "05",
          "Cachorro"
        ],
        [
          "2º",
          "4011",
          "03",
          "Burro"
        ],
        [
          "3º",
          "5161",
          "16",
          "Leão"
        ],
        [
          "4º",
          "3971",
          "18",
          "Porco"
        ],
        [
          "5º",
          "7472",
          "18",
          "Porco"
        ],
        [
          "6º",
          "0453",
          "14",
          "Gato"
        ],
        [
          "7º",
          "8019",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "2167",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "0111",
          "03",
          "Burro"
        ],
        [
          "10º",
          "2185",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8695",
          "24",
          "Veado"
        ],
        [
          "2º",
          "8942",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "3723",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1161",
          "16",
          "Leão"
        ],
        [
          "5º",
          "8287",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "0808",
          "",
          ""
        ],
        [
          "7º [mult]",
          "750",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8695",
          "24",
          "Veado"
        ],
        [
          "2º",
          "8942",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "3723",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1161",
          "16",
          "Leão"
        ],
        [
          "5º",
          "8287",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "8831",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "6971",
          "18",
          "Porco"
        ],
        [
          "8º",
          "9426",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "5231",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "1267",
          "17",
          "Macaco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5690",
          "23",
          "Urso"
        ],
        [
          "2º",
          "7413",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "3156",
          "14",
          "Gato"
        ],
        [
          "4º",
          "3207",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2867",
          "17",
          "Macaco"
        ],
        [
          "6º [soma]",
          "2333",
          "",
          ""
        ],
        [
          "7º [mult]",
          "179",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5690",
          "23",
          "Urso"
        ],
        [
          "2º",
          "7413",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "3156",
          "14",
          "Gato"
        ],
        [
          "4º",
          "3207",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2867",
          "17",
          "Macaco"
        ],
        [
          "6º",
          "5733",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "6412",
          "03",
          "Burro"
        ],
        [
          "8º",
          "9150",
          "13",
          "Galo"
        ],
        [
          "9º",
          "0367",
          "17",
          "Macaco"
        ],
        [
          "10º",
          "3995",
          "24",
          "Veado"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5130",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "1336",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7386",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "3541",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "2240",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "9633",
          "",
          ""
        ],
        [
          "7º [mult]",
          "853",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5130",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "1336",
          "09",
          "Cobra"
        ],
        [
          "3º",
          "7386",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "3541",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "2240",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "5173",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "1335",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "3384",
          "21",
          "Touro"
        ],
        [
          "9º",
          "0661",
          "16",
          "Leão"
        ],
        [
          "10º",
          "0186",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8616",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "4667",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "4449",
          "13",
          "Galo"
        ],
        [
          "4º",
          "9154",
          "14",
          "Gato"
        ],
        [
          "5º",
          "5927",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "2813",
          "",
          ""
        ],
        [
          "7º [mult]",
          "210",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8616",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "4667",
          "17",
          "Macaco"
        ],
        [
          "3º",
          "4449",
          "13",
          "Galo"
        ],
        [
          "4º",
          "9154",
          "14",
          "Gato"
        ],
        [
          "5º",
          "5927",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "8449",
          "13",
          "Galo"
        ],
        [
          "7º",
          "6641",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "1645",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "6794",
          "24",
          "Veado"
        ],
        [
          "10º",
          "6342",
          "11",
          "Cavalo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 12:00 - PTSP",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2999",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "6977",
          "20",
          "Peru"
        ],
        [
          "3º",
          "8062",
          "16",
          "Leão"
        ],
        [
          "4º",
          "2164",
          "16",
          "Leão"
        ],
        [
          "5º",
          "3973",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "4175",
          "",
          ""
        ],
        [
          "7º [mult]",
          "924",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1788",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "0507",
          "02",
          "Águia"
        ],
        [
          "3º",
          "9387",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "0546",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "3198",
          "25",
          "Vaca"
        ],
        [
          "6º [soma]",
          "5426",
          "",
          ""
        ],
        [
          "7º [mult]",
          "906",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1788",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "0507",
          "02",
          "Águia"
        ],
        [
          "3º",
          "9387",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "0546",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "3198",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "1090",
          "23",
          "Urso"
        ],
        [
          "7º",
          "7535",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "8084",
          "21",
          "Touro"
        ],
        [
          "9º",
          "8776",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "0911",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5247",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "3787",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "6380",
          "20",
          "Peru"
        ],
        [
          "4º",
          "2123",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0174",
          "19",
          "Pavão"
        ],
        [
          "6º [soma]",
          "7711",
          "",
          ""
        ],
        [
          "7º [mult]",
          "870",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 15:30 - BANDEIRANTES, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5247",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "3787",
          "22",
          "Tigre"
        ],
        [
          "3º",
          "6380",
          "20",
          "Peru"
        ],
        [
          "4º",
          "2123",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0174",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "5362",
          "16",
          "Leão"
        ],
        [
          "7º",
          "2731",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "4882",
          "21",
          "Touro"
        ],
        [
          "9º",
          "7703",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "8389",
          "23",
          "Urso"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1866",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7809",
          "03",
          "Burro"
        ],
        [
          "3º",
          "0253",
          "14",
          "Gato"
        ],
        [
          "4º",
          "3068",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "6787",
          "22",
          "Tigre"
        ],
        [
          "6º [soma]",
          "9783",
          "",
          ""
        ],
        [
          "7º [mult]",
          "571",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 17hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1866",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "7809",
          "03",
          "Burro"
        ],
        [
          "3º",
          "0253",
          "14",
          "Gato"
        ],
        [
          "4º",
          "3068",
          "17",
          "Macaco"
        ],
        [
          "5º",
          "6787",
          "22",
          "Tigre"
        ],
        [
          "6º",
          "1703",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "8820",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "6056",
          "14",
          "Gato"
        ],
        [
          "9º",
          "6938",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "3300",
          "25",
          "Vaca"
        ]
      ]
    }
  ]
};