const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 21/08/2025 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3966",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "1131",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "5470",
          "18",
          "Porco"
        ],
        [
          "4º",
          "6406",
          "02",
          "Águia"
        ],
        [
          "5º",
          "6284",
          "21",
          "Touro"
        ],
        [
          "6º",
          "1183",
          "21",
          "Touro"
        ],
        [
          "7º",
          "0767",
          "17",
          "Macaco"
        ],
        [
          "8º",
          "2176",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "4963",
          "16",
          "Leão"
        ],
        [
          "10º",
          "9935",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 21/08/2025 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7554",
          "14",
          "Gato"
        ],
        [
          "2º",
          "0248",
          "12",
          "Elefante"
        ],
        [
          "3º",
          "8648",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "5885",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "1444",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "0731",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "7185",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "1720",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "3250",
          "13",
          "Galo"
        ],
        [
          "10º",
          "8752",
          "13",
          "Galo"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 21/08/2025 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6513",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "4419",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0736",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "6016",
          "04",
          "Borboleta"
        ],
        [
          "5º",
          "4826",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "4201",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "9171",
          "18",
          "Porco"
        ],
        [
          "8º",
          "6768",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "3673",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "5399",
          "25",
          "Vaca"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 21/08/2025 (Quinta-feira)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5807",
          "02",
          "Águia"
        ],
        [
          "2º",
          "8625",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "8445",
          "12",
          "Elefante"
        ],
        [
          "4º",
          "5884",
          "21",
          "Touro"
        ],
        [
          "5º",
          "4441",
          "11",
          "Cavalo"
        ],
        [
          "6º",
          "3170",
          "18",
          "Porco"
        ],
        [
          "7º",
          "2717",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "5283",
          "21",
          "Touro"
        ],
        [
          "9º",
          "0051",
          "13",
          "Galo"
        ],
        [
          "10º",
          "2578",
          "20",
          "Peru"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6760",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "6623",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "1056",
          "14",
          "Gato"
        ],
        [
          "4º",
          "4212",
          "03",
          "Burro"
        ],
        [
          "5º",
          "8606",
          "02",
          "Águia"
        ],
        [
          "6º",
          "4379",
          "20",
          "Peru"
        ],
        [
          "7º",
          "0171",
          "18",
          "Porco"
        ],
        [
          "8º",
          "7242",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "7512",
          "03",
          "Burro"
        ],
        [
          "10º",
          "6871",
          "18",
          "Porco"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6860",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "1697",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "1387",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "8324",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "1079",
          "20",
          "Peru"
        ],
        [
          "6º",
          "2090",
          "23",
          "Urso"
        ],
        [
          "7º",
          "8883",
          "21",
          "Touro"
        ],
        [
          "8º",
          "4920",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "2588",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "5578",
          "20",
          "Peru"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1693",
          "24",
          "Veado"
        ],
        [
          "2º",
          "5731",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "6876",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "0339",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "9272",
          "18",
          "Porco"
        ],
        [
          "6º [soma]",
          "3911",
          "",
          ""
        ],
        [
          "7º [mult]",
          "702",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1693",
          "24",
          "Veado"
        ],
        [
          "2º",
          "5731",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "6876",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "0339",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "9272",
          "18",
          "Porco"
        ],
        [
          "6º",
          "1560",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "6783",
          "21",
          "Touro"
        ],
        [
          "8º",
          "9373",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "3169",
          "18",
          "Porco"
        ],
        [
          "10º",
          "4796",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3892",
          "23",
          "Urso"
        ],
        [
          "2º",
          "9398",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "9368",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "7187",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "6051",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "5896",
          "",
          ""
        ],
        [
          "7º [mult]",
          "577",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 09h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3892",
          "23",
          "Urso"
        ],
        [
          "2º",
          "9398",
          "25",
          "Vaca"
        ],
        [
          "3º",
          "9368",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "7187",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "6051",
          "13",
          "Galo"
        ],
        [
          "6º",
          "3997",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "8331",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "9968",
          "17",
          "Macaco"
        ],
        [
          "9º",
          "2887",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "1079",
          "20",
          "Peru"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1783",
          "21",
          "Touro"
        ],
        [
          "2º",
          "9428",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "4016",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "8640",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "9927",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "3794",
          "",
          ""
        ],
        [
          "7º [mult]",
          "810",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 11h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1783",
          "21",
          "Touro"
        ],
        [
          "2º",
          "9428",
          "07",
          "Carneiro"
        ],
        [
          "3º",
          "4016",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "8640",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "9927",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "1948",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "7406",
          "02",
          "Águia"
        ],
        [
          "8º",
          "8214",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "3860",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "5222",
          "06",
          "Cabra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2679",
          "20",
          "Peru"
        ],
        [
          "2º",
          "2891",
          "23",
          "Urso"
        ],
        [
          "3º",
          "5432",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "3029",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "4052",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "8083",
          "",
          ""
        ],
        [
          "7º [mult]",
          "744",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 14h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2679",
          "20",
          "Peru"
        ],
        [
          "2º",
          "2891",
          "23",
          "Urso"
        ],
        [
          "3º",
          "5432",
          "08",
          "Camelo"
        ],
        [
          "4º",
          "3029",
          "08",
          "Camelo"
        ],
        [
          "5º",
          "4052",
          "13",
          "Galo"
        ],
        [
          "6º",
          "2253",
          "14",
          "Gato"
        ],
        [
          "7º",
          "6840",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "7932",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "9129",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "4237",
          "10",
          "Coelho"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1300",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "9519",
          "05",
          "Cachorro"
        ],
        [
          "3º",
          "0833",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "2603",
          "01",
          "Avestruz"
        ],
        [
          "5º",
          "3703",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "1902",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "3586",
          "22",
          "Tigre"
        ],
        [
          "8º",
          "0130",
          "08",
          "Camelo"
        ],
        [
          "9º",
          "0933",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "4509",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9089",
          "23",
          "Urso"
        ],
        [
          "2º",
          "3530",
          "08",
          "Camelo"
        ],
        [
          "3º",
          "4801",
          "01",
          "Avestruz"
        ],
        [
          "4º",
          "7954",
          "14",
          "Gato"
        ],
        [
          "5º",
          "5679",
          "20",
          "Peru"
        ],
        [
          "6º",
          "9347",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "0589",
          "23",
          "Urso"
        ],
        [
          "8º",
          "8305",
          "02",
          "Águia"
        ],
        [
          "9º",
          "9014",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "8308",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0407",
          "02",
          "Águia"
        ],
        [
          "2º",
          "4942",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "4912",
          "03",
          "Burro"
        ],
        [
          "4º",
          "8335",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "3593",
          "24",
          "Veado"
        ],
        [
          "6º",
          "0448",
          "12",
          "Elefante"
        ],
        [
          "7º",
          "4993",
          "24",
          "Veado"
        ],
        [
          "8º",
          "0413",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "7225",
          "07",
          "Carneiro"
        ],
        [
          "10º",
          "5268",
          "17",
          "Macaco"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9885",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "2401",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7421",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "5943",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "2501",
          "01",
          "Avestruz"
        ],
        [
          "6º [soma]",
          "8151",
          "",
          ""
        ],
        [
          "7º [mult]",
          "733",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9885",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "2401",
          "01",
          "Avestruz"
        ],
        [
          "3º",
          "7421",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "5943",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "2501",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "9275",
          "19",
          "Pavão"
        ],
        [
          "7º",
          "8449",
          "13",
          "Galo"
        ],
        [
          "8º",
          "8024",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "5113",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "9012",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7477",
          "20",
          "Peru"
        ],
        [
          "2º",
          "7708",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3374",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "4562",
          "16",
          "Leão"
        ],
        [
          "5º",
          "4621",
          "06",
          "Cabra"
        ],
        [
          "6º [soma]",
          "7742",
          "",
          ""
        ],
        [
          "7º [mult]",
          "632",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7477",
          "20",
          "Peru"
        ],
        [
          "2º",
          "7708",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3374",
          "19",
          "Pavão"
        ],
        [
          "4º",
          "4562",
          "16",
          "Leão"
        ],
        [
          "5º",
          "4621",
          "06",
          "Cabra"
        ],
        [
          "6º",
          "7734",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "4735",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "7076",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "7842",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "5129",
          "08",
          "Camelo"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1047",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "8250",
          "13",
          "Galo"
        ],
        [
          "3º",
          "4741",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "1447",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "4327",
          "07",
          "Carneiro"
        ],
        [
          "6º [soma]",
          "9812",
          "",
          ""
        ],
        [
          "7º [mult]",
          "637",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "1047",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "8250",
          "13",
          "Galo"
        ],
        [
          "3º",
          "4741",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "1447",
          "12",
          "Elefante"
        ],
        [
          "5º",
          "4327",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "1841",
          "11",
          "Cavalo"
        ],
        [
          "7º",
          "0274",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "4544",
          "11",
          "Cavalo"
        ],
        [
          "9º",
          "7017",
          "05",
          "Cachorro"
        ],
        [
          "10º",
          "3488",
          "22",
          "Tigre"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9429",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "6762",
          "16",
          "Leão"
        ],
        [
          "3º",
          "7121",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1111",
          "03",
          "Burro"
        ],
        [
          "5º",
          "9991",
          "23",
          "Urso"
        ],
        [
          "6º [soma]",
          "4414",
          "",
          ""
        ],
        [
          "7º [mult]",
          "758",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 10hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "9429",
          "08",
          "Camelo"
        ],
        [
          "2º",
          "6762",
          "16",
          "Leão"
        ],
        [
          "3º",
          "7121",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "1111",
          "03",
          "Burro"
        ],
        [
          "5º",
          "9991",
          "23",
          "Urso"
        ],
        [
          "6º",
          "9671",
          "18",
          "Porco"
        ],
        [
          "7º",
          "4711",
          "03",
          "Burro"
        ],
        [
          "8º",
          "2621",
          "06",
          "Cabra"
        ],
        [
          "9º",
          "9211",
          "03",
          "Burro"
        ],
        [
          "10º",
          "0628",
          "07",
          "Carneiro"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 12:00 - PTSP",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5497",
          "25",
          "Vaca"
        ],
        [
          "2º",
          "0460",
          "15",
          "Jacaré"
        ],
        [
          "3º",
          "6285",
          "22",
          "Tigre"
        ],
        [
          "4º",
          "7023",
          "06",
          "Cabra"
        ],
        [
          "5º",
          "0318",
          "05",
          "Cachorro"
        ],
        [
          "6º [soma]",
          "9583",
          "",
          ""
        ],
        [
          "7º [mult]",
          "528",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7110",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2151",
          "13",
          "Galo"
        ],
        [
          "3º",
          "2000",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "9863",
          "16",
          "Leão"
        ],
        [
          "5º",
          "4240",
          "10",
          "Coelho"
        ],
        [
          "6º [soma]",
          "5364",
          "",
          ""
        ],
        [
          "7º [mult]",
          "293",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 13hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7110",
          "03",
          "Burro"
        ],
        [
          "2º",
          "2151",
          "13",
          "Galo"
        ],
        [
          "3º",
          "2000",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "9863",
          "16",
          "Leão"
        ],
        [
          "5º",
          "4240",
          "10",
          "Coelho"
        ],
        [
          "6º",
          "7229",
          "08",
          "Camelo"
        ],
        [
          "7º",
          "1108",
          "02",
          "Águia"
        ],
        [
          "8º",
          "1506",
          "02",
          "Águia"
        ],
        [
          "9º",
          "0103",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "5310",
          "03",
          "Burro"
        ]
      ]
    }
  ]
};